services:
  db1:
    image: mysql:8.0
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd-dist
    ports:
      - "3306:3306"
  db2:
    image: mysql:8.0
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd-dist
    ports:
      - "3307:3306"
  db3:
    image: mysql:8.0
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd-dist
    ports:
      - "3308:3306"
